// Token pipeline: renders the TypeScript theme in
// projects/components/src/lib/tokens/ into the two generated files the rest
// of the workspace consumes —
//
//   src/lib/styles/_tokens.scss   the `:root` custom properties (+ responsive retunes)
//   src/lib/tokens/tokens.ts      the typed `tokens` object (`var(--name)` per key)
//
// Usage (from frontend/):  npm run tokens          regenerate
//                          npm run tokens:check    fail if either file is stale (CI)
//
// Node strips the token sources' TypeScript types natively; the resolve hook
// only adds the `.ts` extension Angular-style imports leave off.
import { readFileSync, writeFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import prettier from 'prettier';

registerHooks({
  resolve(specifier, context, next) {
    if (specifier.startsWith('.') && !/\.[cm]?[jt]s$/.test(specifier)) {
      return next(`${specifier}.ts`, context);
    }
    return next(specifier, context);
  },
});

const lib = resolve(dirname(fileURLToPath(import.meta.url)), '../projects/components/src/lib');
const load = (path) => import(pathToFileURL(resolve(lib, path)).href);

const { saturdazeLightTheme, responsiveOverrides } = await load('tokens/themes/index.ts');
const { themeToCss } = await load('tokens/themeToCss.ts');

const banner = (comment) =>
  [
    `${comment} !!! DO NOT EDIT !!!`,
    `${comment} Generated by \`npm run tokens\` from projects/components/src/lib/tokens/.`,
    `${comment} Change the TypeScript theme and regenerate (ADR-013).`,
  ].join('\n');

const scss = `${banner('//')}
//
// Components consume these as CSS custom properties (\`var(--colorNeutralForeground1)\`
// etc.), named exactly as the theme keys — the Fluent UI v9 convention. Never
// hard-code a hex value in a component stylesheet — if a colour is missing,
// add an alias token to the theme first.
//
// Breakpoints live SCSS-side in \`_breakpoints.scss\` (\`$bp-tablet\` /
// \`$bp-desktop\` + the \`respond-to()\` mixin).

${themeToCss(saturdazeLightTheme, responsiveOverrides)}
`;

const ts = `${banner('//')}

import type { Theme } from './types';

/** Every theme token as a CSS variable reference, for styles written in TypeScript. */
export const tokens: Record<keyof Theme, string> = {
${Object.keys(saturdazeLightTheme)
  .map((key) => `  ${key}: 'var(--${key})',`)
  .join('\n')}
};
`;

const outputs = [
  [resolve(lib, 'styles/_tokens.scss'), scss],
  [resolve(lib, 'tokens/tokens.ts'), ts],
];

const check = process.argv.includes('--check');
let stale = false;
for (const [file, source] of outputs) {
  const content = await prettier.format(source, {
    ...(await prettier.resolveConfig(file)),
    filepath: file,
  });
  let current = '';
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    // missing counts as stale
  }
  if (current === content) continue;
  if (check) {
    stale = true;
    console.error(`${file} is out of date — run \`npm run tokens\` in frontend/.`);
  } else {
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
if (stale) process.exit(1);
